**420-SF2-RE: DS & OOP**

**February 12, 2025**

# Assignment #1: drag with coffee filters

For this assignment you will be allowed to use everything that has been covered in class regarding data science libraries.  **Any functions not covered in class will not be allowed to be used and will receive a grade of 0**. 

${\color{red}\text{You should not be making any direct changes to your .csv files.}}\\$
${\color{red}\text{All changes done in this assignment must be done using Python code.}}$

## Part 1: experiment with single coffee filter, 10 runs
**Part 1 DUE DATE: end of class today**

**Part 1 is worth 60% of Assignment #1**

**Part 1 of the assignment is an in-class assignment.  Failure to be in class will receive a grade of 0 for Part 1 of the assignment and late submissions will not be accepted.**


#### Submission: 
- Upload all new and updated files to moodle under ${\color{green}\text{Assignment \#1}}$
- `add`, `commit`, `push` all new and updated files to ${\color{green}\text{git}}$ in your **Assignment #1** folder
- Late submissions of Part 1 (that is, submissions outside of class) will receive a ${\color{red}\text{late penalty}}$. Part 1 may not be submitted later than **Wendesday, February 12 ay 23:59**.

#### Instructions for Part 1:

1. Import all necessary libraries, such as `pandas`, `matplotlib.pyplot`, `numpy`, etc.

In [19]:
# your code for step 1 goes here:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

2. Read  your `.csv` file that has the data of the single filter experiment into a DataFrame called `df`
3. Display the content of the data frame to the screen

In [20]:
# your code for steps 2 and 3 go here:

second_experiment_df = pd.read_csv('Coffee Filter 2.csv') 

second_experiment_df

,Time (s) Run #1,Position (m) Run #1,Velocity (m/s) Run #1,Acceleration (m/s²) Run #1,Time (s) Run #2,Position (m) Run #2,Velocity (m/s) Run #2,Acceleration (m/s²) Run #2,Time (s) Run #3,Position (m) Run #3,...,Velocity (m/s) Run #8,Acceleration (m/s²) Run #8,Time (s) Run #9,Position (m) Run #9,Velocity (m/s) Run #9,Acceleration (m/s²) Run #9,Time (s) Run #10,Position (m) Run #10,Velocity (m/s) Run #10,Acceleration (m/s²) Run #10
0,0.00,1.23,NaN,NaN,0.00,1.34,NaN,NaN,0.00,1.32,...,NaN,NaN,0.00,1.39,NaN,NaN,0.00,1.35,NaN,NaN
1,0.02,1.21,-0.61,NaN,0.02,1.34,-0.35,NaN,0.02,1.30,...,0.30,NaN,0.02,1.39,-0.000827,NaN,0.02,1.35,0.06,NaN
2,0.04,1.20,-0.65,-1.85,0.04,1.33,-0.46,-3.63,0.04,1.31,...,0.26,-5.64,0.04,1.39,-0.040000,-2.27,0.04,1.35,0.02,-2.52
3,0.06,1.19,-0.68,-1.00,0.06,1.32,-0.50,-1.46,0.06,1.31,...,0.08,-8.04,0.06,1.39,-0.090000,-2.15,0.06,1.34,-0.04,-3.46
4,0.08,1.17,-0.70,-0.07,0.08,1.31,-0.47,-0.73,0.08,1.30,...,-0.19,-5.48,0.08,1.38,-0.130000,-0.97,0.08,1.35,-0.16,-2.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

4. Extract from the DataFrame `df` into a new DataFrame `data_df` only the **Time** and **Position** columns for the 10 runs.  Here are the details of how your `data_df` should look: 
- Time column titles should read: **Time (s) Run #$i$** for $0\leq i\leq 10$
- Position column titles should read: **Position (m) Run #$i$** for $0\leq i\leq 10$
- The order of the columns in your `data_df` should first display all the **Time** columns then all the **Position** columns.  
- all NaN values should be dropped from `data_df`
Note that this process should be automated.  You **should not** manually adjust the content of the `data_df` for each run. 
5. Display the content of `data_df`

In [34]:
# Your code for steps 4 and 5 go here:


time_data_df = second_experiment_df[[f'Time (s) Run #{i}' for i in range(1, 11)]] 
position_data_df = second_experiment_df[[f'Position (m) Run #{j}' for j in range(1, 11)]]

data_df = pd.concat([time_data_df, position_data_df], axis = 1)

data_df.dropna(inplace = True)

data_df

,Time (s) Run #1,Time (s) Run #2,Time (s) Run #3,Time (s) Run #4,Time (s) Run #5,Time (s) Run #6,Time (s) Run #7,Time (s) Run #8,Time (s) Run #9,Time (s) Run #10,Position (m) Run #1,Position (m) Run #2,Position (m) Run #3,Position (m) Run #4,Position (m) Run #5,Position (m) Run #6,Position (m) Run #7,Position (m) Run #8,Position (m) Run #9,Position (m) Run #10
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.23,1.34,1.32,1.28,1.18,1.45,1.38,1.33,1.39,1.35
1,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,1.21,1.34,1.30,1.28,1.17,1.43,1.38,1.33,1.39,1.35
2,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,1.20,1.33,1.31,1.28,1.15,1.42,1.38,1.35,1.39,1.35
3,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,1.19,1.32,1.31,1.30,1.13,1.43,1.38,1.35,1.39,1.34
4,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,1.17,1.31,1.30,1.29,1.12,1.42,1.37,1.35,1.38,1.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1.18,1.18,1.18,1.18,1.18,1.18,1.18,1.18,1.18,1.18,0.12,0.32,0.25,0.44,1.37,0.52,0.64,0.44,0.57,0.48
60,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.13,0.30,0.23,0.41,1.40,0.50,0.62,0.42,0.55,0.46
61,1.22,1.22,1.22,1.22,1.22,1.22,1.22,1.22,1.22,1.22,0.14,0.28,0.20,0.39,1.34,0.48,0.60,0.40,0.53,0.43
62,1.24,1.24,1.24,1.24,1.24,1.24,1.24,1.24,1.24,1.24,0.12,0.26,0.18,0.37,1.35,0.46,0.59,0.38,0.51,0.41
63,1.26,1.26,1.26,1.26,1.26,1.26,1.26,1.26,1.26,1.26,0.11,0.24,0.16,0.34,1.30,0.44,0.56,0.36,0.49,0.39

6. The data in `data_df` contains noisy data.  In this step you are to clean the noisy data (or extract the clean data). Your cleaned data **for each run**
- must not include the data that is after once the filter hits the motion sensor
- must include the curved data that transitions into a drop in position.  You should only keep about 0.5 to 1 second of the roughly constant position values before the drop of position takes place.  
Note that you should clean your data for each of the 10 runs and you should automate this process in your code with logical conditions, loops, etc.

7. Store your clean data into a new DataFrame called `clean_df`. 
8. Note that now that the values in the **Time** columns may have shifted due to the clean-up.  Update your `clean_df` to rescale all the **Time** columns to start the time from 0.0 in increments of 0.02. 
9. Write this to a new .csv file called `"clean_data_single_filter.csv"`.

In [40]:
# Your code for steps 6-9 go here:

# step 6


for j in range(1, 11):
    drop_indices = [0, 1, 2, 3]

    position_col = f'Position (m) Run #{j}'

    for i in range(1, len(position_data_df) - 1):
        if data_df[position_col].iloc[i + 1] > position_col.iloc[i]:
            drop_indices.extend((range(i, min(63, len(position_col)))))
    

# step 7 
      
    clean_df = data_df['Position (m) #{j}'].drop(index = set(drop_indices), errors='ignore').drop_duplicates(subset = position_col)

clean_df

# step 8 

# 

# step 9 

# clean_df.to_csv("clean_data_single_filte.csv", index = False)

AttributeError: 'str' object has no attribute 'iloc'

10. Plot the data using `matplotlib` from all 10 runs as scatter plots on the same figure using your cleaned data.  
- Each plot should have a label **Run #$i$** for $1\leq i\leq10$
- The label on the x-axis should read **Time (s)**
- The label on the y-axis should read **Position (m)**
- Each plot should be in a different color and there should be a legend showing which colour is which run. 
- scale the size of the points so that they are not too big.  
Note that you should automate the process of plotting the 10 graphs.

11. Take the last 0.5 to 1 second of the x-values in your 10 runs, and draw a line of best fit on all your 10 graphs.

In [ ]:
# Your code for steps 10-11 go here:
# colors = [blue, yellow, red, green, purple, orange, black, grey, pink, lightblue]
# for i in range(1, 11):
    # xpoints = f'Time (s) Run #{i}'
    # ypoints = f'Position (m) Run #{i}'
    # plt.scatter(xpoints, ypoints , color = colors[i - 1], legend = True)
    # plt.xlim(0, 10)
    # plt.ylim(0, 100)
    # plt.xlabel('Time (s)')
    # plt.ylabel('Position (m)')
    # b, a = np.polyfit(xpoints, ypoints, deg = 2)
    # xseq = np.linspace(0, 10)
    # plt.plot()
    #

### ${\color{green} \text{Submit your work to moodle and git for Part 1 before moving to Part 2}}$

## Part 2: experiment with multiple coffee filters, 10 runs
**Part 2 DUE DATE: Friday, February 14 at 20:00**

**Part 2 is worth 40% of Assignment #1**

#### Submission:
- Upload all new and updated files to moodle under ${\color{green}\text{Assignment \#1}}$.  Make sure to not delete or overwrite any files during your previous submissions.  
- `add`, `commit`, `push` all new and updated files to ${\color{green}\text{git}}$ in your **Assignment #1** folder
- late submissions of Part 2 will receive a grade of 0.


#### Instructions for Part 2:

1. Read  your .csv file that has the data of filters of varying mass into a DataFrame `df`.  
3. Display the content of the DataFrame to the screen

In [ ]:
# Your code for steps 1 and 2 go here:

3. Extract from the DataFrame `df` into a new DataFrame `data_df` only the **Time** and **Position** columns for the 10 runs.  Here are the details of how your `data_df` should look: 
- Time column titles should read: **Time (s) Run #$i$** for $0\leq i\leq 10$
- Position column titles should read: **Position (m) Run #$i$** for $0\leq i\leq 10$
- The order of the columns in your `data_df` should first display all the **Time** columns then all the **Position** columns.  
- all NaN values should be dropped from `data_df`
Note that this process should be automated.
4. Display the content of `data_df`

In [ ]:
# Your code for steps 3 and 4 go here:

5. The data in `data_df` contains noisy data.  In this step you are to clean the noisy data (or extract the clean data). Your cleaned data **for each run**
- must not include the data that is after once the filter hits the motion sensor
- must include only the bit where a drop in position starts.  You should not include any constant position values before the drop of positions takes place.    
Note that you should clean your data for each of the 10 runs and you should automate this process in your code with logical conditions, loops, etc.
6. Store your clean data into a new DataFrame called `clean_df`. 
7. Note that now that the values in the **Time** columns may have shifted due to the clean-up.  Update your `clean_df` to rescale all the **Time** columns to start the time from 0.0 in increments of 0.02. 
8. Write this to a new .csv file called `"clean_data_multiple_filter.csv"`.

In [ ]:
# Your code for steps 5-8 go here:

9. Plot the data from all 10 runs as line plots on the same figure using your cleaned data.  
- Each plot should have a label **Run #$i$** for $1\leq i\leq10$
- The label on the x-axis should read **Time (s)**
- The label on the y-axis should read **Position (m)**
- Each plot should be in a different color and there should be a legend showing which colour is which run.

In [ ]:
# Your code for step 9 goes here: